

<form action="" method="post">
<table border="0" cellpadding="10" cellspacing="0">


            <tr class="odd">
                <th colspan="2" class="left"><?php echo "Applications Settings"?></th>
            </tr>

            <tr>
                <td width="30%"><?php echo "Application URL";?></td>
                <td width="70%"><input type="text" name="APP_URL" size="80"
                                       value="<?php echo $this->config->_url; ?>"
                                       class="input_textbox" /></td>
            </tr>

            <tr>
                <td width="30%"><?php echo "Resource Path";?></td>
                <td width="70%"><input type="text" name="APP_RESOURCE_PATH" size="80"
                                       value="<?php echo $this->config->_resource_path; ?>"
                                       class="input_textbox" /></td>
            </tr>

            <tr class="odd">
                <th colspan="2" class="left"><?php echo "Post Settings"?></th>
            </tr>
            

            <tr>
                <td width="30%"><?php echo "No. of Posts/run (cronjob)";?></td>
                <td width="70%"><input type="text" name="APP_SENDMAIL_POSTCOUNT" size="80"
                                       value="<?php echo $this->config->_sendmail_postcount; ?>"
                                       class="input_textbox" /></td>
            </tr>


            <tr class="odd">
                <th colspan="2" class="left"><?php echo "Facebook Settings"?></th>
            </tr>

            <tr>
                <td width="30%"><?php echo "App Id";?></td>
                <td width="70%"><input type="text" name="APP_FB_APPID" size="80"
                                       value="<?php echo $this->config->_fb_appid; ?>"
                                       class="input_textbox" /></td>
            </tr>

            <tr class="odd">
                <th colspan="2" class="left"><?php echo "Page Settings"?></th>
            </tr>

            <tr>
                <td width="30%"><?php echo "Number of Rows in Table";?></td>
                <td width="70%"><input type="text" name="APP_PAGE_NO_OF_ROWS_IN_TABLE" size="80"
                                       value="<?php echo $this->config->_page_no_of_rows_in_table; ?>"
                                       class="input_textbox" /></td>
            </tr>

            

            <tr>
                
                <td width="70%"><input type="submit" name="submit" size="80"
                                       value="<?php echo "Save"; ?>"
                                       class="submit" /></td>
            </tr>


 </table>

</form>