

 <body>
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            appId      : '<?php echo $this->fbAppId;?>',
            status     : true,
            cookie     : true,
            xfbml      : true
          });
        };
        (function(d){
           var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
           js = d.createElement('script'); js.id = id; js.async = true;
           js.src = "//connect.facebook.net/en_US/all.js";
           d.getElementsByTagName('head')[0].appendChild(js);
         }(document));
      </script>









      <a href="#" id="ff"  class="fb-login-button" onclick="fb()">Get Friends</a>&nbsp;&nbsp;&nbsp;
      
      <br/><br/>

      <script>
      function fb() {console.log('hu');
              FB.login(function(response) {
                       if (response.authResponse) {

                       var accessToken = response.authResponse.accessToken;
window.location.href = 'friends/get/token/'+ accessToken.valueOf();
                                        return false;
                   } else {
                         alert('User cancelled login or did not fully authorize.');
                       }
                     },{scope: 'email,user_groups'});
      }
      </script>














<table class="listings groups">

    	<tr>
    		<th scope="col"  width="100"><?php echo 'No';?></th>
                <th scope="col"  width="100"><?php echo 'Avatar';?></th>
    		<th scope="col"  width="600"><?php echo 'Name';?></th>    		        
    		<th scope="col"  width="100"><?php echo 'Action';?></th>
                <th scope="col"  width="100"><?php echo 'Select';?></th>
                

    	</tr>


        <?php if (count($this->paginator)): ?>
      <form action="" method="post">

  <?php foreach ($this->paginator as $friend):  ?>
    <tr height="30" align="center">
        <td><?php echo (++$this->postCounter); ?> </td>
        <td><img src="https://graph.facebook.com/<?php echo $friend->FbId; ?>/picture"></td>
        <td><a href ="http://facebook.com/<?php echo $friend->FbId; ?>"><?php echo html_entity_decode($friend->Name, ENT_COMPAT, 'UTF-8'); ?></a></td>
        
        

    </tr>


<?php endforeach; ?>


      <tr height="30">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
      <!--   <input type="submit" name="deactivate" size="80" value="activate/deactivate"/></td> -->
      </tr>

     </form>


<?php endif; ?>



</table>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    '/helper/common/pagination.phtml',array("search"=>$this->search)); ?>



  </body>



    